name: Deploy bitforecast server to heroku.

on:
  push:
    branches: [main]

# jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out repository.
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build, Push and Release the Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_directory: ./
          dockerfile_name: Dockerfile

          # Additional options of docker build command.
          docker_options: "--no-cache"

          # Process type of the docker container.
          # By default, this argument is set to "web".
          process_type: web
